<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE impresoras[
  <!ELEMENT impresoras (impresora*) > 
    <!ATTLIST impresoras empresa CDATA #IMPLIED> <!--NO REQUERIDO-->
    <!ELEMENT impresora (marca, modelo, peso, tamaño+, cartucho, enred?) > <!-- PUEDE HABER CERO O MAS IMPRESORAS-->
      <!ATTLIST impresora numSerie CDATA #REQUIRED> <!--REQUERIDO-->
      <!ATTLIST impresora tipo CDATA #REQUIRED> <!--REQUERIDO-->
      <!ATTLIST impresora compra CDATA #IMPLIED> <!--REQUERIDO-->
      <!ELEMENT marca (#PCDATA)>
      <!ELEMENT modelo (#PCDATA)>
      <!ELEMENT peso (#PCDATA)>
      <!ELEMENT tamaño (#PCDATA)> <!--PUEDE APARECER UNA O VARIAS VECES (+)-->
      <!ELEMENT cartucho (#PCDATA)>
      <!ELEMENT enred EMPTY> <!--CAMPO VACIO, PUEDE APARECER O NO (?)-->
]>

<impresoras empresa="IES">
  <impresora numSerie="i245" tipo="láser" compra="2010">
    <marca>Epson</marca>
    <modelo>EPL300</modelo>
    <peso>4.52</peso>
    <tamaño>A4</tamaño>
    <tamaño>A5</tamaño>
    <cartucho>C-12BV</cartucho>
    <enred />
  </impresora>
  <impresora numSerie="i246" tipo="matricial">
    <marca>HP</marca>
    <modelo>LaserJet 2410</modelo>
    <peso>3.2</peso>
    <tamaño>A4</tamaño>
    <cartucho>C-45P</cartucho>
  </impresora>
</impresoras>