<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE torneo[
    <!ELEMENT torneo (participante+)> 
        <!ATTLIST torneo edicion CDATA #REQUIRED>
        <!ATTLIST torneo anteriorGanador CDATA #REQUIRED> <!--REQUERIDO-->
        <!ELEMENT participante (nombre, edad, pais, cabezaDeSerie?)> <!--PUEDE APARECER UNA O VARIAS VECES (+)-->
            <!ATTLIST participante codigo ID #REQUIRED> <!--REQUERIDO, ID-->
            <!ATTLIST participante compañero IDREF #REQUIRED> <!--REQUERIDO, REFERENCIA AL ID DE OTRO-->
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT edad (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>
        <!ELEMENT cabezaDeSerie EMPTY> <!--CAMPO VACIO, PUEDE APARECER O NO (?)-->
]>

<torneo edicion="1998" anteriorGanador="j01">
    <participante codigo="j01" compañero="j02">
        <nombre>Manuel Pérez</nombre>
        <edad>23</edad>
        <pais> España</pais>
        <cabezaDeSerie />
    </participante>
    <participante codigo="j02" compañero="j01">
        <nombre>Manuel Gómez</nombre>
        <edad>25</edad>
        <pais>España</pais>
    </participante>
    <participante codigo="j03" compañero="j04">
        <nombre>Ana Puertas</nombre>
        <edad>22</edad>
        <pais> E5spaña</pais>
        <cabezaDeSerie />
    </participante>
    <participante codigo="j04" compañero="j03">
        <nombre>Paco Fraile</nombre>
        <edad>45</edad>
        <pais>España</pais>
    </participante>
</torneo>