=== AntoSanz/DAW_LMSGI/LMSGI04/Ejercicio1/Sanz_Pans_Antonio_impresoras.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="impresoras" >
    <!--En cada fichero hay datos para una o más impresoras.-->
        <xs:complexType>
            <xs:sequence>
                <xs:element name="impresora" maxOccurs="unbounded"> 
                <!--Todos los elementos son obligatorios, menos enred.-->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca"/>
                            <xs:element name="modelo"/>
                            <xs:element name="peso"> <!--El peso es un número positivo y no puede tener más de dos decimales.-->
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:fractionDigits value="2" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tamaño" maxOccurs="unbounded"/> <!--Puede haber más de un tamaño.-->
                            <xs:element name="cartucho"> <!--El cartucho está formado por una C mayúscula, un guión, dos números y una o dos letras mayúsculas.-->
                            <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:pattern value="C-[0-9][0-9][A-Z][A-Z]"/>
                            </xs:restriction>
                            </xs:simpleType>
                            </xs:element>
                            <xs:element name="enred" minOccurs="0" /> <!--El elemento enred es opcional. De estar presente, es un elemento vacío.-->
                            
                        </xs:sequence>
                        <xs:attribute name="numSerie" use="required" type="xs:ID"/> <!--El atributo numSerie es obligatorio y hace de identificador.-->
                        <xs:attribute name="tipo"> <!--El atributo tipo sólo puede tomar los valores ‘3D’, ‘láser’ y ‘tinta’. Es obligatorio.-->
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                <xs:whiteSpace value="collapse"/>
                                    <xs:enumeration value="3D"/>
                                    <xs:enumeration value="láser"/>
                                    <xs:enumeration value="tinta"/> 
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="compra" type="xs:integer"/> <!--El atributo compra, opcional, guarda el año de compra. Es un número entero positivo.-->
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AntoSanz/DAW_LMSGI/LMSGI04/Ejercicio1/xml_prueba/validos/impresoras_laser.xml
<?xml version="1.0" encoding="UTF-8"?>
<impresoras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Sanz_Pans_Antonio_impresoras.xsd">
  <impresora numSerie="i245" tipo="láser" compra="2010">
    <marca>Epson</marca>
    <modelo>EP A5</modelo>
    <peso>10.01</peso>
    <tamaño>A5</tamaño>
    <cartucho>C-20XL</cartucho>
  </impresora>

  <impresora numSerie="a123" tipo="láser">
    <marca>HP</marca>
    <modelo>Serie L</modelo>
    <peso>3.2</peso>
    <tamaño>10</tamaño>
    <cartucho>C-32CB</cartucho>
  </impresora>

    <impresora numSerie="b123" tipo="láser" compra="2022">
      <marca>Cannon</marca>
      <modelo>SERIE S</modelo>
      <peso>5.12</peso>
      <tamaño>DIN A2</tamaño>
      <tamaño>DIN A3</tamaño>
      <tamaño>DIN A4</tamaño>
      <tamaño>DIN A5</tamaño>
      <cartucho>C-12AB</cartucho>
    </impresora>
  
</impresoras>

=== AntoSanz/DAW_LMSGI/LMSGI04/Ejercicio1/xml_prueba/validos/impresoras_varias.xml
<?xml version="1.0" encoding="UTF-8"?>
<impresoras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Sanz_Pans_Antonio_impresoras.xsd">
  <impresora numSerie="i245" tipo="láser" compra="2010">
    <marca>Epson</marca>
    <modelo>EPL300</modelo>
    <peso>4.52</peso>
    <tamaño>A4</tamaño>
    <tamaño>A5</tamaño>
    <cartucho>C-12BV</cartucho>
    <enred/>
  </impresora>

  <impresora numSerie="a123" tipo="3D">
    <marca>Cannon</marca>
    <modelo>SERIE S</modelo>
    <peso>5.32</peso>
    <tamaño>10</tamaño>
    <cartucho>C-12AB</cartucho>
  </impresora>

    <impresora numSerie="b123" tipo="tinta" compra="2022">
      <marca>Cannon</marca>
      <modelo>SERIE S</modelo>
      <peso>6</peso>
      <tamaño>10</tamaño>
      <cartucho>C-12AB</cartucho>
      <enred/>
    </impresora>
  
</impresoras>

=== AntoSanz/DAW_LMSGI/LMSGI04/Ejercicio1/xml_prueba/novalidos/impresora_id_duplicado.xml
<?xml version="1.0" encoding="UTF-8"?>
<impresoras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Sanz_Pans_Antonio_impresoras.xsd">
  <impresora numSerie="i245" tipo="3D" compra="2010">
    <marca>Epson</marca>
    <modelo>EPL300</modelo>
    <peso>4.52</peso>
    <tamaño>A4</tamaño>
    <tamaño>A5</tamaño>
    <cartucho>C-12AB</cartucho>
    <enred/>
  </impresora>
  
   <impresora numSerie="i245" tipo="3D" compra="2010">
    <marca>Cannon</marca>
    <modelo>Premium</modelo>
    <peso>2</peso>
    <tamaño>A4</tamaño>
    <cartucho>C-12AB</cartucho>
    <enred/>
  </impresora>
</impresoras>

=== AntoSanz/DAW_LMSGI/LMSGI04/Ejercicio1/xml_prueba/validos/impresoras_enred.xml
<?xml version="1.0" encoding="UTF-8"?>
<impresoras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Sanz_Pans_Antonio_impresoras.xsd">
  <impresora numSerie="i245" tipo="láser" compra="2010">
    <marca>Samsung</marca>
    <modelo>M3820ND</modelo>
    <peso>5.10</peso>
    <tamaño>A4</tamaño>
    <tamaño>A5</tamaño>
    <tamaño>A6</tamaño>
    <cartucho>C-20KL</cartucho>
    <enred/>
  </impresora>
  </impresoras>
